### ISSUE TITLE
Add support for linking images on Android

### ISSUE THREAD

**Issue by MiloszFilimowski** [unimonkiez/react-native-asset#27]
Hey 👋 Thanks for creating this awesome package :) 

I store my images on the native side to help with performance. Right now this package works great for iOS, unfortunately Android requires all images to be stores in `drawable` folder (correct me if I'm wrong) and won't load the asset inside `<Image/>` tag. 

Would it be hard to support it?

**Comment by unimonkiez** [comment]
Pretty easy to implement, just add the extensions [here](https://github.com/unimonkiez/react-native-asset/blob/master/lib/index.js#L207), I'll merge and publish that pull request when you're done
