### ISSUE TITLE
Suggestion: Allow ios-only and android-only assets to be specified in react-native.config.js

### ISSUE THREAD

**Issue by rsml** [unimonkiez/react-native-asset#34]
I see you already support linking different files or folders on android vs ios.

However, it'd be really great if the configuration was able to be declared in the `react-native.config.js` file. That way I don't have to create separate scripts to keep track of which files to link on iOS and android. And other users of my project don't have to learn a new way of linking assets.

I think it'd be very nice to have two optional parameters added to `react-native.config.js`, called "assets-ios" and "assets-android".

That way when I run `npx react-native-asset` it would first link the files listed in the `assets` parameter to both platforms, and then it would separately link `assets-ios` to the iOS platform and `assets-android` to Android.

Thanks for this repo by the way!

**Comment by roryabraham** [comment]
Created a PR to implement this suggestion: https://github.com/unimonkiez/react-native-asset/pull/42
