### ISSUE TITLE
Support for TrueType Collection (TTC) fonts

### ISSUE THREAD

**Issue by jmarek-sky** [unimonkiez/react-native-asset#35]
When I try to add a [ttc font](https://en.wikipedia.org/wiki/TrueType#TrueType_Collection), it seems that `react-native-asset` places it in the `custom` folder for Android, instead of the `fonts` directory.

**Comment by roryabraham** [comment]
This is probably because TTC fonts are not supported by iOS https://developer.apple.com/documentation/devicemanagement/font
