### ISSUE TITLE
xmldom@0.5.0 vulnerability with plist dependency

### ISSUE THREAD

**Issue by kennychh** [unimonkiez/react-native-asset#36]
With react-native-asset 2.0.1, the plist dependency (^3.0.1) has a xmldom dependency (^0.5.0) which has a vulnerability issue

**Comment by lucasftcruz** [comment]
@unimonkiez I saw there is a PR open to address this issue, any ETA when it is gonna be released? Thanks for the amazing work btw!

**Comment by unimonkiez** [comment]
Merged in new version 2.1.1
