### ISSUE TITLE
Should bundleInDebug = true

### ISSUE THREAD

**Issue by efleurine** [unimonkiez/react-native-asset#6]
I follow your instruction but I still was not able to load a png file as test.

At the end in `android/app/build.gradle` I added bundleInDebug: true in `project.ext.react`

```
project.ext.react = [
    entryFile: "index.js",
    bundleInDebug: true
]
```

After that I was able to load the image with 

```
<Image
          source={{ uri: asset:/custom/assetlogo.png' }}
          style={{width: 400, height: 400}}
          onError={(e) => console.log('image error \n', e)}
          onLoadEnd={res => console.log('loaded end', res)}
        />
```

Is this the way it should be ?

**Comment by unimonkiez** [comment]
Not need to link images in react-native.  
Simply import them -
```js
import myImage from 'sexy-image.png';

...
<Image
  source={myImage}
/>
```

If you don't like linking as much as I do you can check [this boilerplate](https://github.com/unimonkiez/react-platformula-boilerplate) which uses this library to make linking seamless.

**Comment by efleurine** [comment]
Thanks @unimonkiez  for the boilerplate reference.

I took an image file for easy representation but my goal was more to get a text file. After setting the `bundleInDebug: true` I was able to do.

Yeah, I really don't like linking too.

**Comment by unimonkiez** [comment]
Your fix is just for android, so you should check iOS too.  

> Is this the way it should be ?  

It really depends on what your text file contains.  
If it's a small file, I would just put it as a module, `export default 'some text';` (or if using webpack enabled project, add loader for text files).  
If it's really big and going to increase the execution time of your bundle, lazy loading the file might be the solution.  

I usually avoid lazy loading anything, even if it takes the app 5 seconds to load up, and the experience in the app after load is smooth, I rather have that.
